apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smartmedia.fullname" . }}
  labels:
    {{- include "smartmedia.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smartmedia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smartmedia.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "smartmedia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5559
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /liveness
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /liveness
#              port: http
          volumeMounts:
            - readOnly: true
              mountPath: /etc/conf
              name: situationstatus
            - readOnly: true
              mountPath: /etc/confmod
              name: moduleconfig
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: situationstatus
          configMap:
            name: situationstatus
        - name: moduleconfig
          configMap:
            name: moduleconfig
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
