apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: policy-smartmedia
      - name: kube-mgmt
        securityContext: {}
        args:
          - --require-policy-label
          - --policies={{ .Release.Namespace }}
          - --replicate=katalog.fybrik.io/v1alpha1/assets
        image: openpolicyagent/kube-mgmt:0.11
        imagePullPolicy: IfNotPresent
        resources: { }
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: policy-smartmedia
        configMap:
          name: policy-smartmedia

