apiVersion: v1
kind: ConfigMap
metadata:
  name: moduleconfig
data:
   moduleconfig.yaml:  |
          SAFE_VIDEO_URL: 'http://safe-video-url/'
          SAFE_METADATA_URL: 'http://safe-metadata-url/'
          UNSAFE_VIDEO_URL: 'http://unsafe-video-url/'
          UNSAFE_METADATA_URL: 'http://unsafe-metadata-url/'
    
