apiVersion: v1
data:
  main: |
    package dataapi.authz
 
    rule[{"name": "Only allow administrator GET access to assets when organization is unsafe", "action": "BlockResource"}]{
      input.request.situationStatus == "organization-unsafe"
      input.request.method == "GET"
      input.request.role != "Admin"
    }

    rule[{"name": "Block video-booth_operator from GETting videos", "action": "BlockResource"}]{
      input.request.method == "GET"
      input.request.role == "Video-Booth-User""
      input.request.asset == "videos"
    }
    
    rule[{"name": "Block video-editor from POSTting", "action": "BlockResource"}]{
      input.request.method == "POST"
      input.request.role == "Editor"
    }
    rule[{"name": "Block specific user", "action": "BlockUser"}] {
      input.request.situationStatus == "user-unsafe"
      input.request.user == input.request.unsafeUserName
    }

    rule[{"name": "Block video-editor from GETting surveys", "action": "BlockResource"}]{
      input.request.method == "GET"
      input.request.role == "Editor"
      input.request.asset == "surveys"
    }

    rule[{"name": "Block video-editor from GETting videos if video editor is unsafe", "action": "BlockResource"}]{
      input.request.method == "GET"
      input.request.role == "Editor"
      input.request.asset == "videos"
      input.request.situationStatus == "Editor-unsafe"
    }
    
    rule[{"name": "Block video-booth-operator from GETting surveys if video-booth-operator is unsafe", "action": "BlockResource"}]{
      input.request.method == "GET"
      input.request.role == "video-booth-operator"
      input.request.asset == "surveys"
      input.request.situationStatus == "video-booth-user-unsafe"
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    openpolicyagent.org/policy: rego
  name: policy-smartmedia

